In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [8]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [14]:
X_train

array([[    20,  49000],
       [    46,  88000],
       [    31,  34000],
       [    47,  30000],
       [    35,  50000],
       [    39,  96000],
       [    33, 113000],
       [    49,  86000],
       [    45,  79000],
       [    44,  39000],
       [    41,  59000],
       [    42,  53000],
       [    35,  73000],
       [    41,  72000],
       [    27,  96000],
       [    30, 116000],
       [    41,  52000],
       [    41,  52000],
       [    20,  82000],
       [    46,  41000],
       [    27,  31000],
       [    35,  71000],
       [    49,  28000],
       [    35,  91000],
       [    37,  75000],
       [    32, 117000],
       [    36,  75000],
       [    20,  86000],
       [    38,  50000],
       [    49,  36000],
       [    40,  65000],
       [    37,  77000],
       [    60,  46000],
       [    48, 138000],
       [    40,  71000],
       [    36,  63000],
       [    26,  81000],
       [    33,  31000],
       [    41,  51000],
       [    46,  74000],


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train

array([[-1.68062015e+00, -5.92416706e-01],
       [ 8.69241193e-01,  5.63566526e-01],
       [-6.01832657e-01, -1.03702564e+00],
       [ 9.67312783e-01, -1.15558802e+00],
       [-2.09546297e-01, -5.62776110e-01],
       [ 1.82740063e-01,  8.00691292e-01],
       [-4.05689477e-01,  1.30458142e+00],
       [ 1.16345596e+00,  5.04285335e-01],
       [ 7.71169603e-01,  2.96801165e-01],
       [ 6.73098013e-01, -8.88822663e-01],
       [ 3.78883243e-01, -2.96010749e-01],
       [ 4.76954833e-01, -4.73854323e-01],
       [-2.09546297e-01,  1.18957591e-01],
       [ 3.78883243e-01,  8.93169951e-02],
       [-9.94119017e-01,  8.00691292e-01],
       [-6.99904247e-01,  1.39350321e+00],
       [ 3.78883243e-01, -5.03494919e-01],
       [ 3.78883243e-01, -5.03494919e-01],
       [-1.68062015e+00,  3.85722952e-01],
       [ 8.69241193e-01, -8.29541472e-01],
       [-9.94119017e-01, -1.12594743e+00],
       [-2.09546297e-01,  5.96763994e-02],
       [ 1.16345596e+00, -1.21486922e+00],
       [-2.

In [16]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [21]:
print(classifier.predict(sc.transform([[ 20,  49000]])))

[0]


In [26]:
y_pred = classifier.predict(X_test)

In [27]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1) ), 1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)

In [32]:
cm

array([[52,  6],
       [11, 31]], dtype=int64)

In [33]:
accuracy_score(y_test,y_pred)

0.83